name: Build Qt Project
on:
  # 触发时机
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # 编译矩阵策略
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        qt-version: [6.2.2]
    steps:
      - name: setup Qt on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version }}
          host: 'ubuntu'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '$HOME/Qt'
          cached: true
      - name: setup Qt on Windows
        if: matrix.os == 'windows-2019'
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: 'C:\\Qt'
          cached: true
      - name: Install dependencies on ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgl1-mesa-dev
      
      - name: Install dependencies on Windows
        if: matrix.os == 'windows-2019'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          setx PATH "%PATH%;C:\\Qt\\${{ matrix.qt-version }}\\msvc2019_64\\bin"
          choco install opencv
          setx PATH "%PATH%;C:\\Program Files\\opencv\\build\\x64\\vc15\\bin"

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Move library files to bin directory on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          mv build/lib build/bin/

      - name: Move library files to bin directory on Windows
        if: matrix.os == 'windows-2019'
        run: |
          move build\\lib build\\bin\\
      
      - name: Upload bin artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}-qt-${{ matrix.qt-version }}
          path: build/bin/