name: Ubuntu
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    name: ${{ matrix.build_target }} - ${{ matrix.os }} - build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        qt_ver: [6.2.2]
        qt_arch: [gcc_64]
        # build_type: [Debug, Release]
        # build_target: [install]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - name: ubuntu install GL library
        run: |
          sudo apt update
          sudo apt-get install -y libglew-dev libglfw3-dev cmake g++ make gcc
      - name: checkout
        uses: actions/checkout@v3
        # with:
        #   submodules: 'true'
        #   fetch-depth: 0
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
      - name: Configure CMake
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build

      - name: move lib
        run: mv build/lib build/bin/
      
      - name: Upload bin artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bin-artifacts
          path: build/bin/